accelerator: null
accumulate_grad_batches: 1
activation: TanH
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 64
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
config: config/default_model_config.yaml
data_dir: ../dataset/processed_data
default_root_dir: null
deterministic: false
devices: null
disable_audio: true
distributed_backend: null
dropout: 0.2
dropout_multiplier: 4.0
early_stopping_patience: 10
fast_dev_run: false
first_l_sz: 256
flush_logs_every_n_steps: 100
full_speech_enc_dim: 612
future_context: 20
generated_gestures_dir: null
gpus: 1
gradient_clip_algorithm: norm
gradient_clip_val: 0.0
ipus: null
learning_rate: 0.0001
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
max_epochs: null
max_steps: null
max_time: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_epochs_with_no_autoregression: 7
n_layers: 1
n_prev_poses: 3
no_overwrite_warning: false
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
past_context: 10
plugins: null
precision: 32
prediction_save_formats:
- video
- 3d_coordinates
- raw_gesture
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
result_dir: ../results
resume_from_checkpoint: null
run_name: 20210925_text_only_early_stopping
save_model_every_n_epochs: 0
save_train_predictions_every_n_epoch: 0
save_val_predictions_every_n_epoch: 1
saved_models_dir: null
saved_prediction_duration_sec: 9
second_l_sz: 512
sequence_length: 40
speech_enc_frame_dim: 124
stochastic_weight_avg: false
sync_batchnorm: false
terminate_on_nan: false
text_context: 10
text_embedding: BERT
third_l_sz: 384
tpu_cores: null
track_grad_norm: -1
truncated_bptt_steps: null
use_pca: false
use_recurrent_speech_enc: false
val_check_interval: 1.0
vel_coef: 0.6
weights_save_path: null
weights_summary: top
